### ISSUE TITLE
Set react and react-dom as peerDependencies instead of dependencies

### ISSUE THREAD

**Issue by JoseMartinC** [NeoRaider/react-multi-split-pane#4]
#### Is your feature request related to a problem? Please describe.

The current version introduces `react` and `react-dom` as a dependency. Would be great to set them as peerDependencies in the same way of react-split-pane does.

#### Describe the solution you'd like

I tried to submit a PR but didn't have access. Essentially change `package.json` from
```
	"dependencies": {
		"react": "^16.13.1",
		"react-dom": "^16.13.1"
	},
```
to
```
	"peerDependencies": {
		"react": "^16.13.1",
		"react-dom": "^16.13.1"
	},
```

#### Additional context

Thanks a lot for the work so far in the module! : )

**Comment by neocturne** [comment]
Makes sense, I'll take care of it in the next days.

**Comment by JoseMartinC** [comment]
Awesome! Thank you : )
